---
title: "ReadMe"
---

#Required Packages
`tidyverse`


```{r libraries, echo=FALSE}
library(tidyverse)
library(httr)
library(jsonlite)
```
#API Functions

##Berries
```{r}
berry <- function(type,specific="",limit=100){
  limit = as.character(limit)
  if(!is_character(type)){
    stop("Error: Must be string")
  }
  base <- "https://pokeapi.co/api/v2"
  if(type=="berry"){
    hyperlink <- paste0(base,"/berry/",specific,"/?limit=",limit)
    a<-GET(hyperlink)
    data <- fromJSON(rawToChar(a$content))
    if(specific != ""){
    return(data$item)}
    else{
      return(data$results)}
  }
    else if (type=="firmness"){
      hyperlink <- paste0(base,"/berry-firmness/",specific,"/?limit=",limit)
      a<-GET(hyperlink)
      data <- fromJSON(rawToChar(a$content))
      if(specific != ""){
    return(data$berries)}
    else{
      return(data$results)}
  }
      else if(type=="flavor"){
        hyperlink <- paste0(base,"/berry-flavor/",specific,"/?limit=",limit)
        a<-GET(hyperlink)
        data <- fromJSON(rawToChar(a$content))
        if(specific != ""){
    return(data$berries)}
    else{
      return(data$results)}
  }
        else{
          stop("Error: Must be one of berry,firmness,flavor")
        }
}
```
```
#testing
out<- berry(type="berry",specific = "cheri")
new <- berry(type = "firmness",specific = "soft")
fin <- berry(type = "flavor",specific ="spicy" )

```


##Moves
```{r}
move <- function(type,specific="",val="",limit=1000){
  if(!is_character(type) || !is_character(val)){
    stop("Error: Must be string")
  }
  if(type == "move"){
  base <- "https://pokeapi.co/api/v2/move/"
  link<-paste0(base,specific,"/?limit=",limit)
  a<- GET(link)
  r<- fromJSON((rawToChar(a$content)))
  if(val != ""){return(unlist(r[val]))}
  return(r$results)
  }else if(type == "category"){
      base <- "https://pokeapi.co/api/v2/move-category/"
      link<-paste0(base,specific,"/?limit=",limit)
      a<- GET(link)
      r<- fromJSON((rawToChar(a$content)))
      if(specific != "") return(r$moves)
      else{return(r$results)}
  } else  if(type == "class"){
    base <- "https://pokeapi.co/api/v2/move-damage-class/"
    link<-paste0(base,specific,"/?limit=",limit)
    a<- GET(link)
    r<- fromJSON((rawToChar(a$content)))
    if(specific != ""){return(r$moves)}
    else{return(r$results)}
  } else {
    stop("Error: Must be one of move,category,class")
  }
}
```
```
#testing
au <- move(type="move",specific = "overheat", val="accuracy")
bu <- move(type="category",specific = "damage")
a <- move(type="move",specific = "overheat", val="power")
```

##Pokemon
```{r}
  pokemon <- function(type,specific="",inc=TRUE,limit=1000){
    if(!is_character(type)){
      stop("Error: Must be string")
    } 
  
    if(type=="ability"){
      base <- "https://pokeapi.co/api/v2/ability/"
      link <- paste0(base,specific,"/?limit=",limit)
      a <- GET(link)
      r<- fromJSON(rawToChar(a$content))
      if(specific != ""){return(r$pokemon)}
      return(r)
    }
    if(type == "pokemon"){
      base <- "https://pokeapi.co/api/v2/pokemon/"
      link <- paste0(base,specific,"/?limit=",limit)
      a <- GET(link)
      r<- fromJSON(rawToChar(a$content))
      if(specific!= ""){return(r$weight)}
      else {return(r)}
    }
    if(type == "stats"){
      base <- "https://pokeapi.co/api/v2/stat/"
      link <- paste0(base,specific,"/?limit=",limit)
      a <- GET(link)
      r<- fromJSON(rawToChar(a$content))
      if(specific!=""){
        if(inc){return(r$affecting_moves$increase)}
        else{return(r$affecting_moves$decrease)}
      }
      else{return(r$results)}
    }
  }
  
```

```
  z<-pokemon(type="stats",specific = "attack")
  temp <- "https://pokeapi.co/api/v2/ability/"
  temp2 <- "https://pokeapi.co/api/v2/ability/stench"
  a <- GET(temp3)
  b <- fromJSON((rawToChar(a$content)))
  temp3<- "https://pokeapi.co/api/v2/stat/"
```


##Wrapper
```{r}
  API_Wrapper <- function(fun,...){
    if(!is_character(fun)){
    stop("Error: Must be string for function")
  }
    if(fun=="berry"){
      berry(...)
    }
      else if(fun=="move"){
        move(...)
      }
        else if(fun=="pokemon"){
          pokemon(...)
        }
          else{
            stop("Error: fun must be one of berry, move, pokemon")}
  }
```

#Exploratory Data Analysis
